In [1]:
import numpy as np

# 03.01.

In [2]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

addition = v1 + v2
subtraction = v1 - v2
dot = np.dot(v1, v2)
cross = np.cross(v1,v2)

print(f'{addition}, {subtraction}, {dot}, {cross}')

[5 7 9], [-3 -3 -3], 32, [-3  6 -3]


# 03.02.

In [3]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(f'''
addition:    {(A+B).tolist()}, 
sub:         {(A-B).tolist()}, 
wrong mult:  {(A*B).tolist()}, 
mat mult:    {np.matmul(A,B).tolist()}
transpose A: {np.transpose(A).tolist()}
transpose B: {np.transpose(B).tolist()}''')


addition:    [[6, 8], [10, 12]], 
sub:         [[-4, -4], [-4, -4]], 
wrong mult:  [[5, 12], [21, 32]], 
mat mult:    [[19, 22], [43, 50]]
transpose A: [[1, 3], [2, 4]]
transpose B: [[5, 7], [6, 8]]


# 03.03.

In [4]:
trans = np.array([[0,-1],[1,0]]) #rotation

points = np.array([[1,1],[2,2],[3,3]])
wrong = np.matmul(points,trans)
transformed_points = points @ trans.T

print(f'''
Original Points: {points.tolist()}
Transformed Points: {transformed_points.tolist()} (rotated 90 deg left)
Wrong: {wrong.tolist()}
''')


Original Points: [[1, 1], [2, 2], [3, 3]]
Transformed Points: [[-1, 1], [-2, 2], [-3, 3]] (rotated 90 deg left)
Wrong: [[1, -1], [2, -2], [3, -3]]



# 03.04.

In [5]:
points = np.array([[0,0,0],[1,0,0],
                   [1,1,0],[0,1,0],
                   [0,0,1],[1,0,1],
                   [1,1,1],[0,1,1],])

T_scale = np.array([[2,0,0],
                    [0,2,0],
                    [0,0,2]])

T_rotate = np.array([[0,-1,0],
                    [1,0,0],
                    [0,0,1]])

T_shear = np.array([[1,0,0],
                    [1,1,0],
                    [0,0,1]])

points_scaled = points @ T_scale
points_rotated = points @ T_rotate
points_sheared = points @ T_shear

print(f''''
original: 
{points}

s: 
{points_scaled}

r: 
{points_rotated}

sh: 
{points_sheared}''')


'
original: 
[[0 0 0]
 [1 0 0]
 [1 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 1]
 [1 1 1]
 [0 1 1]]

s: 
[[0 0 0]
 [2 0 0]
 [2 2 0]
 [0 2 0]
 [0 0 2]
 [2 0 2]
 [2 2 2]
 [0 2 2]]

r: 
[[ 0  0  0]
 [ 0 -1  0]
 [ 1 -1  0]
 [ 1  0  0]
 [ 0  0  1]
 [ 0 -1  1]
 [ 1 -1  1]
 [ 1  0  1]]

sh: 
[[0 0 0]
 [1 0 0]
 [2 1 0]
 [1 1 0]
 [0 0 1]
 [1 0 1]
 [2 1 1]
 [1 1 1]]


# 03.05.

In [6]:
import numpy as np

# Define matrix A and vector b
A = np.array([[2, 3],
              [4, 1]])

b = np.array([5, 6])

# Solve for x using NumPy's linear solver
x = np.linalg.solve(A, b)

# Display the result
print("Solution vector x:", x.tolist())


Solution vector x: [1.3, 0.8]


# 03.06.

In [7]:
C = np.array([[4,1],[2,3]])
eval, evec = np.linalg.eig(C) # columns are eigenvectors

print(f'Eigenvalues: {eval}')
print(f'Eigenvectors normalized: \n{evec.tolist()}')

v1_norm = evec[:, 0]  # ~ [0.7071, 0.7071]
v2_norm = evec[:, 1]  # ~ [-0.4472, 0.8944]

v1 = v1_norm / v1_norm[0]
v2 = v2_norm / v2_norm[1]

print(f'''\nEigenvectors neat: 
{np.column_stack([v1,v2])}''')

Eigenvalues: [5. 2.]
Eigenvectors normalized: 
[[0.7071067811865475, -0.4472135954999579], [0.7071067811865475, 0.8944271909999159]]

Eigenvectors neat: 
[[ 1.  -0.5]
 [ 1.   1. ]]


# 03.07.

## Problem 1

In [8]:
import numpy as np
from itertools import combinations

def find_bases(vectors):
    # Convert to numpy arrays
    arrs = [np.array(v) for v in vectors]
    
    # Check all vectors have same dimension
    dims = [len(v) for v in arrs]
    if len(set(dims)) != 1:
        return "The list of vectors contains vectors of different dimensions."
    
    D = dims[0]
    
    # Stack into matrix
    M = np.vstack(arrs)
    rank = np.linalg.matrix_rank(M)
    
    if rank < D:
        return "There are less than D independent vectors in the set."
    
    # Otherwise, find all bases (all subsets of size D with full rank)
    bases = []
    for combo in combinations(arrs, D):
        mat = np.vstack(combo)
        if np.linalg.matrix_rank(mat) == D:
            bases.append(combo)
    
    return bases

# Example
L = [[1,2,3,4],[5,6,7,8],[6,8,10,12],[4,4,4,4],[3,2,1,0]]
print(find_bases(L))


There are less than D independent vectors in the set.


## Problem 2

In [9]:
def projection(v, w):
    v = np.array(v, dtype=float)
    w = np.array(w, dtype=float)
    
    if np.allclose(w, 0):
        raise ValueError("Cannot project onto the zero vector.")
    
    proj = (np.dot(v, w) / np.dot(w, w)) * w
    return proj.astype(int) if np.allclose(proj, np.round(proj)) else proj

# Example
v = [1,2,3,4]
w = [0,0,1,0]
print(projection(v, w))


[0 0 3 0]
